// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mussohmoarxpegzkwcse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11c3NvaG1vYXJ4cGVnemt3Y3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODA1NzEsImV4cCI6MjA2MjU1NjU3MX0.WTbPynBK__FK78Dmz0-jgIa-MhywFr2DaKC3AuRy18I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);